[general]
import = [
    './alacritty_theme.toml'
]

[font]
size = 9

  [font.bold]
  family = "JetBrainsMono Nerd Font"
  style = "Bold"

  [font.bold_italic]
  family = "JetBrainsMono Nerd Font"
  style = "Bold Italic"

  [font.italic]
  family = "JetBrainsMono Nerd Font"
  style = "Italic"

  [font.normal]
  family = "JetBrainsMono Nerd Font"
  style = "Regular"

[window]
decorations = "Transparent"
opacity = 1
blur = true
dynamic_padding = false

  [window.padding]
  x = 0 #10
  y = 0 #30

[cursor]
thickness = 0.2

  [cursor.style]
  shape = "Beam"
  blinking = "Always"

[[keyboard.bindings]]
key = "N"
mods = "Control|Shift"
action = "CreateNewWindow"

[[keyboard.bindings]]
key = "+"
mods = "Control|Shift"
action = "IncreaseFontSize"

[[keyboard.bindings]]
key = "-"
mods = "Control|Shift"
action = "DecreaseFontSize"

[[keyboard.bindings]]
key = "F"
mods = "Control|Shift"
action = "ToggleFullscreen"

[[keyboard.bindings]]
key = "F"
mods = "Control"
action = "ToggleMaximized"

[[keyboard.bindings]]
key = "T"
mods = "Control"
action = "CreateNewTab"
