#! /bin/bash

#
# This script is used to manipulate themes of Hyprthemes.
#
# Usage:
# -t    Change theme
# -m    Change theme mode (light/dark) if it exists
# -d    Enable debug messages (useful for in shell execution)
#
# It MUST be used only after setup.sh has been executed inside a shell. 
# It detects if setup.sh has never been launched.
#
#
# Before doing anything, it detects if all the dependencies are installed.
# (Must be moved to setup.sh)
# 
# It checks if the current theme is in light or dark mode to preserve the mode
# after a call to change.
#

source "./include/colors.sh"

function changeTheme()
{
        # DEBUG:
        if [[ "${opt_d}" -eq 1 ]]; then
                printf "${DB} Theme changed to ${1}\n"
                printf "${DB}\$HYPRTHEME = ${1}\n\n"
        fi

        export HYPRTHEME=${1}
        
        # swww
        if ! swww img --transition-duration 1 --transition-fps 59 \
        --transition-type right --transition-step 25 \
        "${HYPRTHEMES_DIR}/${1}/Wallpapers/background.png" \
        1> "/dev/null" 2>&1; then
                if [[ "${opt_d}" -eq 1 ]]; then
                        printf "${DB} ${C}swww${N} could not change the "
                        printf "wallpaper.\n"
                fi
        fi
        
        # Hyprland
        command cp -f "${HYPRTHEMES_DIR}/${1}/hypr/hyprland.conf" \
        "${HOME}/.config/hypr/hyprland.conf" 1> "/dev/null" 2>&1

        # Change environment variable to know which theme is applied 
        # at next launch
        echo "DO NOT EDIT THIS FILE" \
        1> "${HOME}/.config/hypr/hyprland_theme.conf"
        echo "${1}" 1>> "${HOME}/.config/hypr/hyprland_theme.conf"

        # Hyprlock
        echo "source = ${HYPRTHEMES_DIR}/${1}/hypr/hyprlock/hyprlock.conf" \
        1> "${HOME}/.config/hypr/hyprlock.conf"

        # Rofi
        command cp -f "${HYPRTHEMES_DIR}/${1}/rofi/config.rasi" \
        "${HOME}/.config/rofi/config.rasi" 1> "/dev/null" 2>&1


        # Waybar
        command cp -rf "${HYPRTHEMES_DIR}/${1}/waybar/" "${HOME}/.config/" \
        1> "/dev/null" 2>&1
        killall waybar 1> "/dev/null" 2>&1
        hyprctl dispatch exec waybar 1> "/dev/null" 2>&1

        # Alacritty
        # command cp -rf "${HOME}/.config/themes/${1}/alacritty" "${HOME}/.config"
        echo "general.import = [ \"${HYPRTHEMES_DIR}/GENERIC/alacritty/alacritty.toml\" ]" \
        1> "${HOME}/.config/alacritty/alacritty.toml"

        echo "general.import = [ \"${HYPRTHEMES_DIR}/${1}/alacritty/alacritty.toml\" ]" \
        1> "/${HOME}/.config/themes/GENERIC/alacritty/alacritty_theme.toml"

        # swaync
        # command cp -rf "${HYPRTHEMES_DIR}/${1}/swaync" "${HOME}/.config"
        # killall swaync
        # hyprctl dispatch exec swaync
        # 
}

function main() 
{
        # Init colors
        _colors

        # Defined in ${HOME}/.config/hypr/hyprland_theme.conf
        HYPRTHEME=$(tail -1 "${HOME}/.config/hypr/hyprland_theme.conf")
        
        # HYPRTHEMES_DIR -> Defined in .bashrc and/or .zshrc        

        declare -A themes_list=(
                ["1"]="JapanesePaper"
                ["2"]="JapaneseStone"
        )

        impacted_directories=(
                "hypr"
                "waybar"
                "rofi"
                "alacritty"
                "swaync"
        )

        echo "${THEMES_DIR}"

        local opt_t=0 # Change theme
        local opt_m=0 # Change theme mode (light/dark)
        local opt_d=0 # Enable debug

        # Used to check is an option is used
        local _opt=0

        OPTIND=1

        while getopts "tmd" opt; do
                _opt=1
                case "${opt}" in
                        t) opt_t=1 ;;
                        m) opt_m=1 ;;
                        d) opt_d=1 ;;
                        *) exit 1 ;;
                esac
        done

        shift $((OPTIND-1))

        if [[ "${_opt}" -eq 0 ]]; then
                printf "This script must be used with options.\n"
                exit 1
        fi

        if [[ "${opt_t}" -eq 1 && "${opt_m}" -eq 1 ]]; then
                if [[ "${opt_d}" -eq 1 ]]; then
                        printf "${DB} Only -t or -m can be applied. Not both.\n"
                fi
                exit 1
        fi

        if [[ "${opt_t}" -eq 1 ]]; then
                for i in "${impacted_directories[@]}"; do 
                        command mkdir -p "${HOME}/.config/${i}"
                done

                case "${HYPRTHEME}" in
                        "UNDEFINED") changeTheme "${themes_list[1]}" ;;
                        "JapanesePaper") changeTheme "${themes_list[2]}" ;;
                        "JapaneseStone") changeTheme "${themes_list[1]}" ;;
                esac
        fi

        if [[ "${opt_m}" -eq 1 ]]; then
                change_theme_mode
        fi

        exit 0
}

main "${@}"
